services:
    web:
        image: fholzer/nginx-brotli:latest
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - .:/var/www:delegated
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./cert.pem:/etc/nginx/cert.pem
            - ./cert.key:/etc/nginx/cert.key
        links:
            - php

    php:
        restart: unless-stopped
        build:
            context: docker/php
        volumes:
            - .:/var/www:delegated
